### ISSUE TITLE
クエスト一覧APIの設計と実装

### ISSUE THREAD

**Issue by CornerSyrup** [hal-tokyo-cello/cello-functions#2]
クエスト一覧画面に使うAzure Functions APIの設計

## インフラ

データベース(CosmoDB・MongoDB)関連

- [x] hal-tokyo-cello/cello-functions#3

## アプリ

Azure Functions関連

- [x] hal-tokyo-cello/cello-functions#6
- [x] hal-tokyo-cello/cello-core#6
- [ ] #14
- [ ] #15
